import React, { useEffect, useState } from "react";
import "./Singers.scss"
import { useNavigate } from "react-router-dom";
import Scroll from "../../components/Scroll/Scroll";
function Singers() {
    return (
        <>
            <div className="Singers">
                <Scroll>
                    <div><div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div>
                        <div>100</div></div>

                </Scroll>
            </div>
        </>
    )
}
export default React.memo(Singers)
