export const CHANGE_SINGER_LIST = 'singers/SINGER_LIST'
export const CHANGE_LOADING = 'singers/LOADING'
export const CHANGE_PULLUP_LOADING = 'singers/PULLUP_LOADING'
export const CHANGE_PULLDOWN_LOADING = 'singers/PULLDOWN_LOADING'
export const CHANGE_PAGECOUNT = 'singers/PAGECOUNT'
